dist: trusty
sudo: required
language: node_js

matrix:
  fast_finish: true
  include:
    - node_js: 8

install:
  - yarn
  - yarn global add ganache-cli
  - cp referenceFiles/test.env .
  - mv test.env .env

script:
  - yarn ci